"""
AetherVault -- passphrase-protected key vault + authenticated file encryption
=============================================================================

This replaces the earlier "generate a key, print it, tell the user to save it
by hand" behaviour with a real, if intentionally simple, key-management layer:

  * Keys generated by the Aether engine are stored in a local keystore file,
    each encrypted with AES-256-GCM under a key derived from a master
    passphrase via scrypt (a memory-hard KDF). The passphrase and the derived
    key never touch the disk; only salt, nonce and ciphertext are stored.

  * Files are encrypted with AES-256-GCM. The output carries a small versioned
    header, the nonce, and (optionally) a reference to the keystore entry that
    holds the key -- so a file can be decrypted later with just the passphrase,
    instead of the user copy-pasting a raw hex key.

This is a portfolio/educational key manager, not a substitute for a hardened
KMS or an HSM. It is deliberately transparent about that in the README.
"""

from __future__ import annotations

import json
import os
import base64
from dataclasses import dataclass, asdict
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.scrypt import Scrypt

# Aether's own entropy engine is the key source when available; otherwise we
# fall back to the OS CSPRNG so the vault still works without the Rust core.
try:
    from utility.keygen import AetherKeyGen
except Exception:
    AetherKeyGen = None


# scrypt work factors (interactive-use defaults).
_SCRYPT_N = 2 ** 15
_SCRYPT_R = 8
_SCRYPT_P = 1
_KEY_LEN = 32          # AES-256
_MAGIC = b"AEV2"       # file format marker


def _b64e(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")


def _b64d(s: str) -> bytes:
    return base64.b64decode(s.encode("ascii"))


def _derive_key(passphrase: str, salt: bytes) -> bytes:
    kdf = Scrypt(salt=salt, length=_KEY_LEN, n=_SCRYPT_N, r=_SCRYPT_R, p=_SCRYPT_P)
    return kdf.derive(passphrase.encode("utf-8"))


@dataclass
class KeystoreEntry:
    name: str
    salt: str        # b64
    nonce: str       # b64
    ciphertext: str  # b64 (the encrypted 32-byte key)


class AetherVault:
    def __init__(self, keystore_path: str = "aether_keystore.json"):
        self.keystore_path = Path(keystore_path)
        # Try the Aether engine as the key source; if the Rust core is not
        # built, fall back silently to the OS CSPRNG.
        self._keygen = None
        if AetherKeyGen is not None:
            try:
                self._keygen = AetherKeyGen()
            except Exception:
                self._keygen = None

    # -- entropy ------------------------------------------------------------

    def _fresh_key(self) -> bytes:
        """32 random bytes from the Aether engine, or the OS CSPRNG fallback."""
        if self._keygen is not None:
            return self._keygen.generate_bytes(_KEY_LEN)
        return os.urandom(_KEY_LEN)

    # -- keystore -----------------------------------------------------------

    def _load_store(self) -> dict[str, dict]:
        if not self.keystore_path.exists():
            return {}
        return json.loads(self.keystore_path.read_text())

    def _save_store(self, store: dict[str, dict]) -> None:
        self.keystore_path.write_text(json.dumps(store, indent=2))

    def store_key(self, name: str, passphrase: str, key: bytes | None = None) -> bytes:
        """Generate (or accept) a key, encrypt it under the passphrase, and
        save it in the keystore under `name`. Returns the plaintext key."""
        if key is None:
            key = self._fresh_key()
        salt = os.urandom(16)
        derived = _derive_key(passphrase, salt)
        nonce = os.urandom(12)
        ct = AESGCM(derived).encrypt(nonce, key, name.encode("utf-8"))
        entry = KeystoreEntry(name, _b64e(salt), _b64e(nonce), _b64e(ct))
        store = self._load_store()
        store[name] = asdict(entry)
        self._save_store(store)
        return key

    def load_key(self, name: str, passphrase: str) -> bytes:
        """Decrypt and return the stored key for `name`."""
        store = self._load_store()
        if name not in store:
            raise KeyError(f"No key named {name!r} in keystore")
        e = store[name]
        derived = _derive_key(passphrase, _b64d(e["salt"]))
        return AESGCM(derived).decrypt(_b64d(e["nonce"]), _b64d(e["ciphertext"]),
                                       name.encode("utf-8"))

    def list_keys(self) -> list[str]:
        return sorted(self._load_store().keys())

    # -- file encryption ----------------------------------------------------

    def encrypt_file(self, file_path: str, key_name: str, passphrase: str) -> str:
        """Encrypt a file under a keystore key. The key is created and stored
        on first use of `key_name`, so the caller only ever needs the
        passphrase to get the file back. Output: <file_path>.aether"""
        store = self._load_store()
        if key_name in store:
            key = self.load_key(key_name, passphrase)
        else:
            key = self.store_key(key_name, passphrase)

        nonce = os.urandom(12)
        data = Path(file_path).read_bytes()
        name_bytes = key_name.encode("utf-8")
        # header: MAGIC | len(name) | name | nonce, all authenticated as AAD
        header = _MAGIC + len(name_bytes).to_bytes(1, "big") + name_bytes
        ct = AESGCM(key).encrypt(nonce, data, header)

        out_path = file_path + ".aether"
        Path(out_path).write_bytes(header + nonce + ct)
        return out_path

    def decrypt_file(self, encrypted_path: str, passphrase: str) -> str:
        """Decrypt an .aether file using only the passphrase; the key name is
        read from the file header and resolved against the keystore."""
        blob = Path(encrypted_path).read_bytes()
        if blob[:4] != _MAGIC:
            raise ValueError("Not an Aether v2 file (bad magic header)")
        name_len = blob[4]
        key_name = blob[5:5 + name_len].decode("utf-8")
        header = blob[:5 + name_len]
        nonce = blob[5 + name_len:5 + name_len + 12]
        ct = blob[5 + name_len + 12:]

        key = self.load_key(key_name, passphrase)
        data = AESGCM(key).decrypt(nonce, ct, header)

        out_path = encrypted_path[:-len(".aether")] if encrypted_path.endswith(".aether") \
            else encrypted_path + ".decrypted"
        if out_path == encrypted_path:
            out_path += ".decrypted"
        Path(out_path).write_bytes(data)
        return out_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _prompt_passphrase() -> str:
    import getpass
    env = os.environ.get("AETHER_VAULT_PASSPHRASE")
    if env:
        return env
    return getpass.getpass("Vault passphrase: ")


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description="Aether Vault -- encrypted key store & file crypto")
    sub = ap.add_subparsers(dest="cmd", required=True)

    pe = sub.add_parser("encrypt", help="encrypt a file")
    pe.add_argument("file")
    pe.add_argument("--key-name", default="default")

    pd = sub.add_parser("decrypt", help="decrypt an .aether file")
    pd.add_argument("file")

    sub.add_parser("list", help="list stored key names")

    args = ap.parse_args()
    vault = AetherVault()

    if args.cmd == "encrypt":
        pw = _prompt_passphrase()
        out = vault.encrypt_file(args.file, args.key_name, pw)
        print(f"[+] Encrypted -> {out}  (key '{args.key_name}' in keystore)")
    elif args.cmd == "decrypt":
        pw = _prompt_passphrase()
        out = vault.decrypt_file(args.file, pw)
        print(f"[+] Decrypted -> {out}")
    elif args.cmd == "list":
        keys = vault.list_keys()
        print("Stored keys:" if keys else "Keystore is empty.")
        for k in keys:
            print(f"  - {k}")
